name: Build Python to APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: # Cho phép bạn bấm nút tự build thủ công nếu muốn

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get Buildozer Cache
      uses: actions/cache@v4
      with:
        path: .buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}

    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v3
      with:
        command: buildozer android debug
        repository_txt: false

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: python-android-apk
        path: bin/*.apk
        